apiVersion: v1
kind: Service
metadata:
  name: front-end-cluster
  
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
      # nodePort: 30008
  selector:
    app: myapp
    type: front-end
