apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: example
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  hostIPC: false
  hostPID: false
  hostNetwork: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 20000
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'
